version: '1'

services:
  airflow:
    build:
      context: airflow

    volumes:
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"

    command: airflow standalone

  nginx:
    image: nginx:latest
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      # - app
      - airflow

    ports:
      - "80:80"